### ISSUE TITLE
Crash: Error: read ECONNRESET

### ISSUE THREAD

**Issue by boneskull** [cgrossde/Pullover#106]
Pullover v1.2.0 on macOS 10.13
here's [the logfile](https://gist.github.com/boneskull/8b863123151208132261e303eb95fa95)

```
Sun Nov 05 2017 22:13:23 GMT-0800 (PST)  Settings             'Settings loaded'   { windowWidth: 450,
  windowHeight: 330,
  displayTime: 7,
  nativeNotifications: true,
  maxNotificationAmount: 5,
  runOnStartup: true,
  defaultSound: 'no' }
Sun Nov 05 2017 22:13:23 GMT-0800 (PST)  NotificationManager   'maxNotificationAmount'   5
Sun Nov 05 2017 22:13:23 GMT-0800 (PST)  ConnectionManager    'fetchAndConnect'
Sun Nov 05 2017 22:13:23 GMT-0800 (PST)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sun Nov 05 2017 22:13:23 GMT-0800 (PST)  UpdateCheck          'Check for update'
Sun Nov 05 2017 22:13:23 GMT-0800 (PST)  Settings             'Changed 'runOnStartup''   true
Sun Nov 05 2017 22:13:24 GMT-0800 (PST)  UpdateCheck          'No update available'   '1.2.0'
Sun Nov 05 2017 22:13:24 GMT-0800 (PST)  ConnectionManager    'Received 0 notifications'
...
Tue Nov 07 2017 03:16:55 GMT-0800 (PST)  ConnectionManager    'fetchAndConnect'
Tue Nov 07 2017 03:16:55 GMT-0800 (PST)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                'Pullover v1.2.0'
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                '=============== STACK ==============='
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)'
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                '=============== Error Object ==============='
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                '{
    stack: 'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)',
    message: 'read ECONNRESET',
    code: 'ECONNRESET',
    errno: 'ECONNRESET',
    syscall: 'read'
}'
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                'Pullover v1.2.0'
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                '=============== STACK ==============='
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)'
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                '=============== Error Object ==============='
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                '{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)', message: 'socket hang up', code: 'ECONNRESET' }'
Tue Nov 07 2017 03:17:19 GMT-0800 (PST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Nov 07 2017 03:17:25 GMT-0800 (PST)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Could not reach Pushover servers]
  name: 'FetchNotificationsFailed',
  cause: 
   { [Error: getaddrinfo ENOTFOUND api.pushover.net api.pushover.net:443]
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'api.pushover.net',
     host: 'api.pushover.net',
     port: 443 } }
Tue Nov 07 2017 03:17:25 GMT-0800 (PST)  ConnectionManager    'Offline'
Tue Nov 07 2017 03:17:55 GMT-0800 (PST)  ConnectionManager    'Checking internet connection'
Tue Nov 07 2017 03:17:56 GMT-0800 (PST)  ConnectionManager    'We are online again'
Tue Nov 07 2017 03:17:56 GMT-0800 (PST)  ConnectionManager    'fetchAndConnect'
```

**Comment by cgrossde** [comment]
Please try the new alpha, it should be fixed there: [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)
If not please reopen this issue ;)
