### ISSUE TITLE
Crash: FetchNotificationsFailed connect ETIMEDOUT

### ISSUE THREAD

**Issue by squaregoldfish** [cgrossde/Pullover#107]
```
Wed Nov 08 2017 09:37:58 GMT+0100 (CET)  Settings             'Settings loaded'   { windowWidth: 450,
  windowHeight: 330,
  displayTime: 7,
  nativeNotifications: true,
  maxNotificationAmount: 20,
  runOnStartup: false,
  defaultSound: 'no' }
Wed Nov 08 2017 09:37:58 GMT+0100 (CET)  NotificationManager   'maxNotificationAmount'   20
Wed Nov 08 2017 09:37:59 GMT+0100 (CET)  ConnectionManager    'fetchAndConnect'
Wed Nov 08 2017 09:37:59 GMT+0100 (CET)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Wed Nov 08 2017 09:37:59 GMT+0100 (CET)  UpdateCheck          'Check for update'
Wed Nov 08 2017 09:37:59 GMT+0100 (CET)  Settings             'Changed 'runOnStartup''   false
Wed Nov 08 2017 09:38:00 GMT+0100 (CET)  UpdateCheck          'No update available'   '1.2.0-alpha.1'
Wed Nov 08 2017 09:38:01 GMT+0100 (CET)  ConnectionManager    'Received 1 notifications'
...
Wed Nov 08 2017 11:09:45 GMT+0100 (CET)  ConnectionManager    'Received 0 notifications'
Wed Nov 08 2017 11:09:45 GMT+0100 (CET)  ConnectionManager    'Connect to WebSocket'
Wed Nov 08 2017 11:10:55 GMT+0100 (CET)  PushoverWSClient     'Socket timed out'
Wed Nov 08 2017 11:10:55 GMT+0100 (CET)  ConnectionManager    'Offline'
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                'Pullover v1.2.0-alpha.1'
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                '=============== STACK ==============='
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                'Error: connect ETIMEDOUT 108.59.9.173:443
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:984:14)'
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                '=============== Error Object ==============='
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                '{
    stack: 'Error: connect ETIMEDOUT 108.59.9.173:443
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:984:14)',
    message: 'connect ETIMEDOUT 108.59.9.173:443',
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '108.59.9.173',
    port: 443
}'
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                'Pullover v1.2.0-alpha.1'
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                '=============== STACK ==============='
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)'
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                '=============== Error Object ==============='
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                '{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)', message: 'socket hang up', code: 'ECONNRESET' }'
Wed Nov 08 2017 11:11:00 GMT+0100 (CET)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Wed Nov 08 2017 11:11:25 GMT+0100 (CET)  ConnectionManager    'Checking internet connection'
Wed Nov 08 2017 11:11:55 GMT+0100 (CET)  ConnectionManager    'Checking internet connection'
Wed Nov 08 2017 11:12:25 GMT+0100 (CET)  ConnectionManager    'Checking internet connection'
Wed Nov 08 2017 11:12:55 GMT+0100 (CET)  ConnectionManager    'Checking internet connection'
```

**Comment by cgrossde** [comment]
Please try the new alpha, it should be fixed there: [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)
If not please reopen this issue ;)
