### ISSUE TITLE
Crash: lastNotificationId is not defined

### ISSUE THREAD

**Issue by Maverine** [cgrossde/Pullover#108]
Pullover fatal error, v. 1.2.0, Windows 10
```
Sat Dec 16 2017 07:14:47 GMT+0100 (Rom, normaltid)  Settings             'Settings loaded'   { windowWidth: 450,
  windowHeight: 330,
  displayTime: 5,
  nativeNotifications: false,
  maxNotificationAmount: 20,
  runOnStartup: true,
  defaultSound: 'no' }
Sat Dec 16 2017 07:14:47 GMT+0100 (Rom, normaltid)  NotificationManager   'maxNotificationAmount'   20
Sat Dec 16 2017 07:14:47 GMT+0100 (Rom, normaltid)  ConnectionManager    'fetchAndConnect'
Sat Dec 16 2017 07:14:47 GMT+0100 (Rom, normaltid)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sat Dec 16 2017 07:14:47 GMT+0100 (Rom, normaltid)  UpdateCheck          'Check for update'
Sat Dec 16 2017 07:14:47 GMT+0100 (Rom, normaltid)  Settings             'Changed 'runOnStartup''   true
Sat Dec 16 2017 07:14:47 GMT+0100 (Rom, normaltid)  UpdateCheck          'No update available'   '1.2.0'
Sat Dec 16 2017 07:14:48 GMT+0100 (Rom, normaltid)  ConnectionManager    'Received 8 notifications'
...
Sat Dec 16 2017 11:12:53 GMT+0100 (Rom, normaltid)  ConnectionManager    'Received 2 notifications'
Sat Dec 16 2017 11:12:53 GMT+0100 (Rom, normaltid)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Sat Dec 16 2017 11:13:31 GMT+0100 (Rom, normaltid)  PushoverWSClient     'notification'
Sat Dec 16 2017 11:13:31 GMT+0100 (Rom, normaltid)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sat Dec 16 2017 11:13:31 GMT+0100 (Rom, normaltid)  ConnectionManager    'Received 1 notifications'
Sat Dec 16 2017 11:13:31 GMT+0100 (Rom, normaltid)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Sat Dec 16 2017 11:13:58 GMT+0100 (Rom, normaltid)  PushoverWSClient     'notification'
Sat Dec 16 2017 11:13:58 GMT+0100 (Rom, normaltid)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sat Dec 16 2017 11:13:59 GMT+0100 (Rom, normaltid)  ConnectionManager    'Received 2 notifications'
Sat Dec 16 2017 11:13:59 GMT+0100 (Rom, normaltid)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Sat Dec 16 2017 11:14:25 GMT+0100 (Rom, normaltid)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Sat Dec 16 2017 11:14:25 GMT+0100 (Rom, normaltid)  Fatal                'Pullover v1.2.0'
Sat Dec 16 2017 11:14:25 GMT+0100 (Rom, normaltid)  Fatal                '=============== STACK ==============='
Sat Dec 16 2017 11:14:25 GMT+0100 (Rom, normaltid)  Fatal                'ReferenceError: lastNotificationId is not defined
    at file:///C:/Users//AppData/Local/Temp/nw5184_15896/app.js:3479:91
    at tryCallOne (file:///C:/Users//AppData/Local/Temp/nw5184_15896/vendors.js:64401:13)
    at file:///C:/Users//AppData/Local/Temp/nw5184_15896/vendors.js:64487:16
    at flush (file:///C:/Users//AppData/Local/Temp/nw5184_15896/vendors.js:64633:30)
    at process._tickCallback (node.js:375:11)'
Sat Dec 16 2017 11:14:25 GMT+0100 (Rom, normaltid)  Fatal                '=============== Error Object ==============='
Sat Dec 16 2017 11:14:25 GMT+0100 (Rom, normaltid)  Fatal                '{ stack: 'ReferenceError: lastNotificationId is not defined
    at file:///C:/Users//AppData/Local/Temp/nw5184_15896/app.js:3479:91
    at tryCallOne (file:///C:/Users//AppData/Local/Temp/nw5184_15896/vendors.js:64401:13)
    at file:///C:/Users//AppData/Local/Temp/nw5184_15896/vendors.js:64487:16
    at flush (file:///C:/Users//AppData/Local/Temp/nw5184_15896/vendors.js:64633:30)
    at process._tickCallback (node.js:375:11)', message: 'lastNotificationId is not defined' }'
Sat Dec 16 2017 11:14:25 GMT+0100 (Rom, normaltid)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Sat Dec 16 2017 11:14:47 GMT+0100 (Rom, normaltid)  ConnectionManager    'Reconnect after 30 min'
Sat Dec 16 2017 11:14:47 GMT+0100 (Rom, normaltid)  ConnectionManager    'Reconnect'
Sat Dec 16 2017 11:14:47 GMT+0100 (Rom, normaltid)  ConnectionManager    'fetchAndConnect'
Sat Dec 16 2017 11:14:47 GMT+0100 (Rom, normaltid)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sat Dec 16 2017 11:15:06 GMT+0100 (Rom, normaltid)  PushoverWSClient     'Socket closed'
Sat Dec 16 2017 11:15:08 GMT+0100 (Rom, normaltid)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
  name: 'FetchNotificationsFailed',
  cause: 
   { [Error: connect ETIMEDOUT 162.216.6.175:443]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '162.216.6.175',
     port: 443 } }
Sat Dec 16 2017 11:15:08 GMT+0100 (Rom, normaltid)  ConnectionManager    'Offline'
```

**Comment by cgrossde** [comment]
Will be fixed with next release.
