### ISSUE TITLE
SyntaxError: Unexpected token <\n

### ISSUE THREAD

**Issue by yeled** [cgrossde/Pullover#36]
I saw this crash this morning. I've added a lot more pushover last night. Could it be related?

```
 Mon Dec 21 2015 09:59:40 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._parseCommand'^M
 Mon Dec 21 2015 09:59:40 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._resetKeepAlive'^M
 Mon Dec 21 2015 09:59:40 GMT+0000 (GMT)  App      'Conn-status:'   1^M
 Mon Dec 21 2015 09:59:40 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype.lastInteractionDate'^M
 Mon Dec 21 2015 09:59:40 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype.lastInteractionDate'^M
 Mon Dec 21 2015 09:59:40 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._stopKeepAlive'^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      '=============== STACK ==============='^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      'SyntaxError: Unexpected token <\n    at Object.parse (native)\n    at validateResponse (/Applications/pullover.app/Contents/      Resources/app.nw/lib/pushover-client.js:744:23)\n    at Request._callback (/Applications/pullover.app/Contents/Resources/app.nw/lib/pushover-client.js:319:4)\n    at Request.self.  callback (/Applications/pullover.app/Contents/Resources/app.nw/node_modules/request/request.js:368:22)\n    at emitTwo (events.js:85:13)\n    at Request.emit (events.js:153:        7)\n    at Request.<anonymous> (/Applications/pullover.app/Contents/Resources/app.nw/node_modules/request/request.js:1219:14)\n    at emitOne (events.js:80:20)\n    at Request.     emit (events.js:150:7)\n    at IncomingMessage.<anonymous> (/Applications/pullover.app/Contents/Resources/app.nw/node_modules/request/request.js:1167:12)'^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      '=============== Error Object ==============='^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      '{ stack: \'SyntaxError: Unexpected token <\\n    at Object.parse (native)\\n    at validateResponse (/Applications/pullover.app/  Contents/Resources/app.nw/lib/pushover-client.js:744:23)\\n    at Request._callback (/Applications/pullover.app/Contents/Resources/app.nw/lib/pushover-client.js:319:4)\\n    at     Request.self.callback (/Applications/pullover.app/Contents/Resources/app.nw/node_modules/request/request.js:368:22)\\n    at emitTwo (events.js:85:13)\\n    at Request.emit         (events.js:153:7)\\n    at Request.<anonymous> (/Applications/pullover.app/Contents/Resources/app.nw/node_modules/request/request.js:1219:14)\\n    at emitOne (events.js:80:        20)\\n    at Request.emit (events.js:150:7)\\n    at IncomingMessage.<anonymous> (/Applications/pullover.app/Contents/Resources/app.nw/node_modules/request/request.js:1167:12)\',   message: \'Unexpected token <\' }'^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      'Show Modal'   'Fatal error'   'Pullover encountered a fatal error. Please goto <a onclick="gui.Shell.openExternal(\'https://      github.com/cgrossde/Pullover/issues\');" href="#">Github (Pullover/Issues)</a> create a new issue and post the contents of your logfile: <a onclick="gui.Shell.showItemInFolder(\'/  Users/charlie/Library/Application\\ Support/Pullover/pullover.1.log\');" href="#">/Users/charlie/Library/Application\\ Support/Pullover/pullover.1.log</a>'   'danger select-        text'   [ { text: 'Exit Pullover', func: [Function] } ]^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._parseCommand'^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._resetKeepAlive'^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  App      'Conn-status:'   1^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype.lastInteractionDate'^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype.lastInteractionDate'^M
 Mon Dec 21 2015 09:59:50 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._stopKeepAlive'^M
 Mon Dec 21 2015 10:00:01 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._parseCommand'^M
 Mon Dec 21 2015 10:00:01 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._resetKeepAlive'^M
 Mon Dec 21 2015 10:00:01 GMT+0000 (GMT)  App      'Conn-status:'   1^M
 Mon Dec 21 2015 10:00:01 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype.lastInteractionDate'^M
 Mon Dec 21 2015 10:00:01 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype.lastInteractionDate'^M
 Mon Dec 21 2015 10:00:01 GMT+0000 (GMT)  OpenClient      'OpenClient.prototype._stopKeepAlive'^M
```

**Comment by cgrossde** [comment]
It seems you had a message with a `\n` line break and Pullover could not parse the response from Pushover to valid JSON: https://github.com/cgrossde/Pullover/blob/5c3aed7e52a79f7576cb1101cfe0a2573101ceca/src/lib/pushover-client.js#L744

Do you have some notifications with line breaks and if so: could you try to reproduce this error by sending one of them?

**Comment by yeled** [comment]
I am confident that the message was from [Sonarr](https://github.com/Sonarr/Sonarr) but I'm having trouble reproducing it.

**Comment by cgrossde** [comment]
Also could not reproduce it with HTML tags or line breaks. Will close for now. Please reopen if you can reproduce it somehow.
