### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by cgrossde** [cgrossde/Pullover#47]
Should be caught ... but is not fatal, client recovered without problems.
```
Sat Mar 12 2016 15:46:33 GMT+0100 (CET)  ConnectionManager      'Connect to WebSocket'
Sat Mar 12 2016 17:28:33 GMT+0100 (CET)  ConnectionManager      'Device woke up after 6108s of sleep'
Sat Mar 12 2016 17:28:33 GMT+0100 (CET)  ConnectionManager      'Reconnect'
Sat Mar 12 2016 17:28:33 GMT+0100 (CET)  ConnectionManager      'fetchAndConnect'
Sat Mar 12 2016 17:28:33 GMT+0100 (CET)  PushoverRESTClient      'OpenClient.prototype.fetchNotifications'
Sat Mar 12 2016 17:28:35 GMT+0100 (CET)  Fatal      ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Sat Mar 12 2016 17:28:35 GMT+0100 (CET)  Fatal      'Pullover v1.0.0-beta.1'
Sat Mar 12 2016 17:28:35 GMT+0100 (CET)  Fatal      '=============== STACK ==============='
Sat Mar 12 2016 17:28:35 GMT+0100 (CET)  Fatal      'Error: getaddrinfo ENOTFOUND client.pushover.net client.pushover.net:443
    at errnoException (dns.js:25:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:75:26)'
Sat Mar 12 2016 17:28:35 GMT+0100 (CET)  Fatal      '=============== Error Object ==============='
Sat Mar 12 2016 17:28:35 GMT+0100 (CET)  Fatal      '{
    stack: 'Error: getaddrinfo ENOTFOUND client.pushover.net client.pushover.net:443
    at errnoException (dns.js:25:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:75:26)',
    message: 'getaddrinfo ENOTFOUND client.pushover.net client.pushover.net:443',
    code: 'ENOTFOUND',
    errno: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'client.pushover.net',
    host: 'client.pushover.net',
    port: 443
}'
Sat Mar 12 2016 17:28:35 GMT+0100 (CET)  Fatal      ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Sat Mar 12 2016 17:28:37 GMT+0100 (CET)  ConnectionManager      'Fetch failed - offline'   { [FetchNotificationsFailed: Could not reach Pushover servers]
  name: 'FetchNotificationsFailed',
  cause: 
   { [Error: getaddrinfo ENOTFOUND api.pushover.net api.pushover.net:443]
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'api.pushover.net',
     host: 'api.pushover.net',
     port: 443 } }
Sat Mar 12 2016 17:28:38 GMT+0100 (CET)  ConnectionManager      'Offline'
```

**Comment by cgrossde** [comment]
Seems to be related to visionmedia/superagent#714

**Comment by cgrossde** [comment]
Mitigated in [1.0.0-beta.2](https://github.com/cgrossde/Pullover/releases/tag/1.0.0-beta.2)

**Comment by cgrossde** [comment]
Closing since super agent is no longer used.
