### ISSUE TITLE
Errot Pullover Start

### ISSUE THREAD

**Issue by Laupe** [cgrossde/Pullover#55]
```
Sat May 28 2016 20:12:04 GMT+0200 (Střední Evropa (letní čas))  Settings             'Settings loaded'   { displayTime: 15,
  nativeNotifications: false,
  maxNotificationAmount: 20,
  runOnStartup: true }
Sat May 28 2016 20:12:08 GMT+0200 (Střední Evropa (letní čas))  NotificationManager   'maxNotificationAmount'   20
Sat May 28 2016 20:12:08 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'fetchAndConnect'
Sat May 28 2016 20:12:08 GMT+0200 (Střední Evropa (letní čas))  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sat May 28 2016 20:12:08 GMT+0200 (Střední Evropa (letní čas))  UpdateCheck          'Check for update'
Sat May 28 2016 20:12:39 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'Device woke up after 19s of sleep'
Sat May 28 2016 20:12:39 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'Reconnect'
Sat May 28 2016 20:12:39 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'fetchAndConnect'
Sat May 28 2016 20:12:39 GMT+0200 (Střední Evropa (letní čas))  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sat May 28 2016 20:12:39 GMT+0200 (Střední Evropa (letní čas))  Settings             'Changed 'runOnStartup''   true
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  UpdateCheck          'No update available'   '1.0.0-beta.3'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'Received 0 notifications'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'Connect to WebSocket'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'Received 0 notifications'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  ConnectionManager    'Connect to WebSocket'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  PushoverWSClient     'Connected'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  Fatal                'Pullover v1.0.0-beta.3'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  Fatal                '=============== STACK ==============='
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  Fatal                'Error: not opened
    at WebSocket.send (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/vendors.js:94747:17)
    at WebSocket.<anonymous> (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/app.js:2213:23)
    at emitNone (events.js:65:13)
    at WebSocket.emit (events.js:147:7)
    at WebSocket.establishConnection (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/vendors.js:95391:9)
    at ClientRequest.upgrade (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/vendors.js:95282:26)
    at ClientRequest.g (events.js:240:16)
    at emitThree (events.js:95:13)
    at ClientRequest.emit (events.js:156:7)
    at TLSSocket.socketOnData (_http_client.js:319:11)'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  Fatal                '=============== Error Object ==============='
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  Fatal                '{ stack: 'Error: not opened
    at WebSocket.send (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/vendors.js:94747:17)
    at WebSocket.<anonymous> (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/app.js:2213:23)
    at emitNone (events.js:65:13)
    at WebSocket.emit (events.js:147:7)
    at WebSocket.establishConnection (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/vendors.js:95391:9)
    at ClientRequest.upgrade (file:///C:/Users/Pavel/AppData/Local/Temp/nw6816_4457/vendors.js:95282:26)
    at ClientRequest.g (events.js:240:16)
    at emitThree (events.js:95:13)
    at ClientRequest.emit (events.js:156:7)
    at TLSSocket.socketOnData (_http_client.js:319:11)', message: 'not opened' }'
Sat May 28 2016 20:12:41 GMT+0200 (Střední Evropa (letní čas))  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Sat May 28 2016 20:12:44 GMT+0200 (Střední Evropa (letní čas))  PushoverWSClient     'Connected'
Sat May 28 2016 20:13:41 GMT+0200 (Střední Evropa (letní čas))  PushoverWSClient     'Socket closed'
```

**Comment by cgrossde** [comment]
Did this happen again?

**Comment by cgrossde** [comment]
Closing for now, please reopen if it happens again.
