### ISSUE TITLE
Fatal error ECONNRESET

### ISSUE THREAD

**Issue by nitalaut** [cgrossde/Pullover#63]
Every time after opening my laptop lid I get this error.
Pullover version(1.1.0-alpha.1). OS X El Capitan 10.11.6

[pullover.1.txt](https://github.com/cgrossde/Pullover/files/389932/pullover.1.txt)
[pullover.2.txt](https://github.com/cgrossde/Pullover/files/389934/pullover.2.txt)
[pullover.3.txt](https://github.com/cgrossde/Pullover/files/389935/pullover.3.txt)
[pullover.4.txt](https://github.com/cgrossde/Pullover/files/389933/pullover.4.txt)
[pullover.5.txt](https://github.com/cgrossde/Pullover/files/389936/pullover.5.txt)

**Comment by willzone1** [comment]
I have the same issue: Every time I wake my PC from sleep, Pullover has experienced a "fatal error." My logs are attached. Lenovo T450s running Windows 10. Pullover version 1.0.0. Logs attached.
[logs.zip](https://github.com/cgrossde/Pullover/files/448572/logs.zip)

**Comment by cgrossde** [comment]
Hmm, I'm not sure why those exceptions are not caught. Please try the new 1.2.0-alpha which has updated dependencies and a notification history: https://github.com/cgrossde/Pullover/releases/tag/1.2.0-alpha.1

Please report back if you are still experiencing these problems with the 1.2.0-alpha.1 version.

**Comment by willzone1** [comment]
After upgrading to 1.2.0-alpha.1 I haven't seen this issue anymore! Thanks @cgrossde !

**Comment by MarkWahlsten** [comment]
Same issue, crashing after waking. I will try updating

Mac osx vers 10.10.5
Pullover vers 1.2.0

Details in the attached log: 
[pullover.1.log.zip](https://github.com/cgrossde/Pullover/files/483935/pullover.1.log.zip)

**Comment by cgrossde** [comment]
Type of errors occurring (for future reference):

**1.2.0:**
This one occurred after a socket error (for full log see below)
```
{ stack: 'ReferenceError: lastNotificationId is not defined
    at file:///Applications/Pullover.app/Contents/Resources/app.nw/app.js:3479:91
    at tryCallOne (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64401:13)
    at file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64487:16
    at flush (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64633:30)
    at process._tickCallback (node.js:375:11)', message: 'lastNotificationId is not defined' }
```

From #71:

```
{
    stack: 'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)',
    message: 'read ECONNRESET',
    code: 'ECONNRESET',
    errno: 'ECONNRESET',
    syscall: 'read'
}
```
And right after:
```
{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)', 
  message: 'socket hang up', 
  code: 'ECONNRESET' }
```

**pre 1.2.0:**
```
[Error: getaddrinfo ENOTFOUND api.pushover.net api.pushover.net:443]
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'api.pushover.net',
     host: 'api.pushover.net',
     port: 443 }
```

```
{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)', 
  message: 'socket hang up', 
  code: 'ECONNRESET' }
```

```
{
    stack: 'Error: read ENETDOWN
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)',
    message: 'read ENETDOWN',
    code: 'KNETDOWN',
    errno: 'KNETDOWN',
    syscall: 'read'
}
```

-------------------
Full excerpt from log regarding first error:

```
Mon Oct 03 2016 06:13:35 GMT+0200 (CEST)  ConnectionManager    'Received 1 notifications'
Mon Oct 03 2016 06:13:35 GMT+0200 (CEST)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Mon Oct 03 2016 06:13:35 GMT+0200 (CEST)  ConnectionManager    'Connect to WebSocket'
Mon Oct 03 2016 06:13:35 GMT+0200 (CEST)  ConnectionManager    'Offline'
Mon Oct 03 2016 06:13:35 GMT+0200 (CEST)  PushoverWSClient     'Socket error: '   { [Error: getaddrinfo ENOTFOUND client.pushover.net client.pushover.net:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'client.pushover.net',
  host: 'client.pushover.net',
  port: 443 }
Mon Oct 03 2016 06:13:36 GMT+0200 (CEST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Oct 03 2016 06:13:36 GMT+0200 (CEST)  Fatal                'Pullover v1.2.0'
Mon Oct 03 2016 06:13:36 GMT+0200 (CEST)  Fatal                '=============== STACK ==============='
Mon Oct 03 2016 06:13:36 GMT+0200 (CEST)  Fatal                'ReferenceError: lastNotificationId is not defined
    at file:///Applications/Pullover.app/Contents/Resources/app.nw/app.js:3479:91
    at tryCallOne (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64401:13)
    at file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64487:16
    at flush (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64633:30)
    at process._tickCallback (node.js:375:11)'
Mon Oct 03 2016 06:13:36 GMT+0200 (CEST)  Fatal                '=============== Error Object ==============='
Mon Oct 03 2016 06:13:36 GMT+0200 (CEST)  Fatal                '{ stack: 'ReferenceError: lastNotificationId is not defined
    at file:///Applications/Pullover.app/Contents/Resources/app.nw/app.js:3479:91
    at tryCallOne (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64401:13)
    at file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64487:16
    at flush (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:64633:30)
    at process._tickCallback (node.js:375:11)', message: 'lastNotificationId is not defined' }'
Mon Oct 03 2016 06:13:36 GMT+0200 (CEST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Oct 03 2016 06:14:05 GMT+0200 (CEST)  ConnectionManager    'Checking internet connection'
Mon Oct 03 2016 06:14:06 GMT+0200 (CEST)  ConnectionManager    'We are online again'
```

**Comment by cgrossde** [comment]
Will track this for 1.2.0 in #106
