### ISSUE TITLE
ReferenceError: lastNotificationId is not defined  

### ISSUE THREAD

**Issue by Ore4444** [cgrossde/Pullover#77]
Pullover v1.2.0

log file:
```
Tue Dec 13 2016 19:33:11 GMT+0200 (Jerusalem Standard Time)  Settings             'Settings loaded'   { windowWidth: 450,
  windowHeight: 330,
  displayTime: 7,
  nativeNotifications: false,
  maxNotificationAmount: 20,
  runOnStartup: true,
  defaultSound: 'po' }
Tue Dec 13 2016 19:33:11 GMT+0200 (Jerusalem Standard Time)  NotificationManager   'maxNotificationAmount'   20
Tue Dec 13 2016 19:33:11 GMT+0200 (Jerusalem Standard Time)  UpdateCheck          'Check for update'
Tue Dec 13 2016 19:33:11 GMT+0200 (Jerusalem Standard Time)  Settings             'Changed 'runOnStartup''   true
Tue Dec 13 2016 19:33:12 GMT+0200 (Jerusalem Standard Time)  UpdateCheck          'No update available'   '1.2.0'
Tue Dec 13 2016 19:33:21 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.registerDevice'
Tue Dec 13 2016 19:33:23 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'fetchAndConnect'
Tue Dec 13 2016 19:33:23 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Tue Dec 13 2016 19:33:23 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Received 1 notifications'
Tue Dec 13 2016 19:33:23 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Tue Dec 13 2016 19:33:24 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Connect to WebSocket'
Tue Dec 13 2016 19:33:56 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Offline'
Tue Dec 13 2016 19:33:56 GMT+0200 (Jerusalem Standard Time)  PushoverWSClient     'Socket error: '   { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Tue Dec 13 2016 19:34:17 GMT+0200 (Jerusalem Standard Time)  Settings             'Changed 'nativeNotifications''   true
Tue Dec 13 2016 19:34:18 GMT+0200 (Jerusalem Standard Time)  Settings             'Changed 'nativeNotifications''   false
Tue Dec 13 2016 19:34:26 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Checking internet connection'
Tue Dec 13 2016 19:34:26 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'We are online again'
Tue Dec 13 2016 19:34:26 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'fetchAndConnect'
Tue Dec 13 2016 19:34:26 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Tue Dec 13 2016 19:34:53 GMT+0200 (Jerusalem Standard Time)  Settings             'Changed 'nativeNotifications''   true
Tue Dec 13 2016 19:34:57 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
  name: 'FetchNotificationsFailed',
  cause: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
Tue Dec 13 2016 19:34:57 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Offline'
Tue Dec 13 2016 19:35:27 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Checking internet connection'
Tue Dec 13 2016 19:35:27 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'We are online again'
Tue Dec 13 2016 19:35:27 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'fetchAndConnect'
Tue Dec 13 2016 19:35:27 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Tue Dec 13 2016 19:35:28 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Received 1 notifications'
Tue Dec 13 2016 19:35:28 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Tue Dec 13 2016 19:35:28 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Connect to WebSocket'
Tue Dec 13 2016 19:35:29 GMT+0200 (Jerusalem Standard Time)  PushoverWSClient     'Connected'
Tue Dec 13 2016 19:35:30 GMT+0200 (Jerusalem Standard Time)  PushoverWSClient     'notification'
Tue Dec 13 2016 19:35:30 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Tue Dec 13 2016 19:35:31 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Received 0 notifications'
Tue Dec 13 2016 19:35:46 GMT+0200 (Jerusalem Standard Time)  Settings             'Changed 'nativeNotifications''   false
Tue Dec 13 2016 19:36:12 GMT+0200 (Jerusalem Standard Time)  PushoverWSClient     'notification'
Tue Dec 13 2016 19:36:12 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Tue Dec 13 2016 19:36:12 GMT+0200 (Jerusalem Standard Time)  ConnectionManager    'Received 1 notifications'
Tue Dec 13 2016 19:36:12 GMT+0200 (Jerusalem Standard Time)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Tue Dec 13 2016 19:37:13 GMT+0200 (Jerusalem Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Tue Dec 13 2016 19:37:13 GMT+0200 (Jerusalem Standard Time)  Fatal                'Pullover v1.2.0'
Tue Dec 13 2016 19:37:13 GMT+0200 (Jerusalem Standard Time)  Fatal                '=============== STACK ==============='
Tue Dec 13 2016 19:37:13 GMT+0200 (Jerusalem Standard Time)  Fatal                'ReferenceError: lastNotificationId is not defined
    at file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/app.js:3479:91
    at tryCallOne (file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/vendors.js:64401:13)
    at file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/vendors.js:64487:16
    at flush (file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/vendors.js:64633:30)
    at process._tickCallback (node.js:375:11)'
Tue Dec 13 2016 19:37:13 GMT+0200 (Jerusalem Standard Time)  Fatal                '=============== Error Object ==============='
Tue Dec 13 2016 19:37:13 GMT+0200 (Jerusalem Standard Time)  Fatal                '{ stack: 'ReferenceError: lastNotificationId is not defined
    at file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/app.js:3479:91
    at tryCallOne (file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/vendors.js:64401:13)
    at file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/vendors.js:64487:16
    at flush (file:///C:/Users/ORE~1.LAN/AppData/Local/Temp/nw6480_31030/vendors.js:64633:30)
    at process._tickCallback (node.js:375:11)', message: 'lastNotificationId is not defined' }'
Tue Dec 13 2016 19:37:13 GMT+0200 (Jerusalem Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
```

**Comment by cgrossde** [comment]
Thanks for reporting, will track this in #108
