### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by b0red** [cgrossde/Pullover#80]
```
Sun Jan 15 2017 22:52:40 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Offline'
Sun Jan 15 2017 22:53:10 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Checking internet connection'
Sun Jan 15 2017 22:53:10 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'We are online again'
Sun Jan 15 2017 22:53:10 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'fetchAndConnect'
Sun Jan 15 2017 22:53:10 GMT+0100 (W. Europe Standard Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Sun Jan 15 2017 22:53:11 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Received 0 notifications'
Sun Jan 15 2017 22:53:11 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Connect to WebSocket'
Sun Jan 15 2017 22:53:12 GMT+0100 (W. Europe Standard Time)  PushoverWSClient     'Connected'
Mon Jan 16 2017 21:58:05 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:05 GMT+0100 (W. Europe Standard Time)  Fatal                'Pullover v1.2.0'
Mon Jan 16 2017 21:58:05 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== STACK ==============='
Mon Jan 16 2017 21:58:05 GMT+0100 (W. Europe Standard Time)  Fatal                'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)'
Mon Jan 16 2017 21:58:05 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== Error Object ==============='
Mon Jan 16 2017 21:58:05 GMT+0100 (W. Europe Standard Time)  Fatal                '{
    stack: 'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)',
    message: 'read ECONNRESET',
    code: 'ECONNRESET',
    errno: 'ECONNRESET',
    syscall: 'read'
}'
Mon Jan 16 2017 21:58:05 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
  name: 'FetchNotificationsFailed',
  cause: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Offline'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                'Pullover v1.2.0'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== STACK ==============='
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== Error Object ==============='
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '{
    stack: 'Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at TCP.onread (net.js:531:26)',
    message: 'read ECONNRESET',
    code: 'ECONNRESET',
    errno: 'ECONNRESET',
    syscall: 'read'
}'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
  name: 'FetchNotificationsFailed',
  cause: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Offline'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
  name: 'FetchNotificationsFailed',
  cause: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Offline'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Fetch failed - offline'   { [FetchNotificationsFailed: Fetch notification request failed]
  name: 'FetchNotificationsFailed',
  cause: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Offline'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  PushoverWSClient     'Socket closed'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                'Pullover v1.2.0'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== STACK ==============='
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== Error Object ==============='
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)', message: 'socket hang up', code: 'ECONNRESET' }'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                'Pullover v1.2.0'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== STACK ==============='
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '=============== Error Object ==============='
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                '{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketCloseListener (_http_client.js:224:23)
    at emitOne (events.js:80:20)
    at TLSSocket.emit (events.js:150:7)
    at TCP.close (net.js:457:12)', message: 'socket hang up', code: 'ECONNRESET' }'
Mon Jan 16 2017 21:58:06 GMT+0100 (W. Europe Standard Time)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon Jan 16 2017 21:58:36 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'Checking internet connection'
Mon Jan 16 2017 21:58:36 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'We are online again'
Mon Jan 16 2017 21:58:36 GMT+0100 (W. Europe Standard Time)  ConnectionManager    'fetchAndConnect'
Mon Jan 16 2017 21:58:36 GMT+0100 (W. Europe Standard Time)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
```

**Comment by cgrossde** [comment]
Duplicate: #63
