### ISSUE TITLE
nw-notify: Could not set style on domElement

### ISSUE THREAD

**Issue by andveg38** [cgrossde/Pullover#83]
[pullover.2.txt](https://github.com/cgrossde/Pullover/files/727102/pullover.2.txt)

**Comment by cgrossde** [comment]
Seems to be a problem with the non native notifications (nw-notify).
```
{ stack: 'Error: nw-notify: Could not set style on domElement
    at setStyleOnDomElement (file:///C:/Users/Andres/AppData/Local/Temp/nw14200_6568/vendors.js:129515:12)
    at Window.<anonymous> (file:///C:/Users/Andres/AppData/Local/Temp/nw14200_6568/vendors.js:129478:8)
    at emitNone (events.js:65:13)
    at Window.emit (events.js:147:7)
    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:786:26)', message: 'nw-notify: Could not set style on domElement' }
```

**Comment by cgrossde** [comment]
nw-notify will be removed in the next release. Will close this issue.
