### ISSUE TITLE
Crash: Error: not opened     at WebSocket.send 

### ISSUE THREAD

**Issue by BodoHuber** [cgrossde/Pullover#96]
I got an fatal error just recently which resuilted in the following log:
[pullover.1.log.txt](https://github.com/cgrossde/Pullover/files/1016791/pullover.1.log.txt)

I run Pullover 1.2.0 under Mac OS 10.12.4
```
Fri May 12 2017 21:26:11 GMT+0200 (CEST)  Settings             'Settings loaded'   { windowWidth: 450,
  windowHeight: 330,
  displayTime: 7,
  nativeNotifications: false,
  maxNotificationAmount: 20,
  runOnStartup: true,
  defaultSound: 'po' }
Fri May 12 2017 21:26:11 GMT+0200 (CEST)  NotificationManager   'maxNotificationAmount'   20
Fri May 12 2017 21:26:11 GMT+0200 (CEST)  ConnectionManager    'fetchAndConnect'
Fri May 12 2017 21:26:11 GMT+0200 (CEST)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Fri May 12 2017 21:26:11 GMT+0200 (CEST)  UpdateCheck          'Check for update'
Fri May 12 2017 21:26:11 GMT+0200 (CEST)  UpdateCheck          'No update available'   '1.2.0'
Fri May 12 2017 21:26:12 GMT+0200 (CEST)  Settings             'Changed 'runOnStartup''   true
Fri May 12 2017 21:26:12 GMT+0200 (CEST)  ConnectionManager    'Received 0 notifications'
Mon May 15 2017 10:43:05 GMT+0200 (CEST)  ConnectionManager    'fetchAndConnect'
Mon May 15 2017 10:43:05 GMT+0200 (CEST)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Mon May 15 2017 10:43:05 GMT+0200 (CEST)  ConnectionManager    'Received 0 notifications'
Mon May 15 2017 10:43:05 GMT+0200 (CEST)  ConnectionManager    'Connect to WebSocket'
Mon May 15 2017 10:43:05 GMT+0200 (CEST)  ConnectionManager    'Received 0 notifications'
Mon May 15 2017 10:43:05 GMT+0200 (CEST)  ConnectionManager    'Connect to WebSocket'
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  PushoverWSClient     'Connected'
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  Fatal                'Pullover v1.2.0'
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  Fatal                '=============== STACK ==============='
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  Fatal                'Error: not opened
    at WebSocket.send (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:105178:17)
    at WebSocket.<anonymous> (file:///Applications/Pullover.app/Contents/Resources/app.nw/app.js:2188:24)
    at emitNone (events.js:65:13)
    at WebSocket.emit (events.js:147:7)
    at WebSocket.establishConnection (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:105846:9)
    at ClientRequest.upgrade (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:105737:26)
    at ClientRequest.g (events.js:240:16)
    at emitThree (events.js:95:13)
    at ClientRequest.emit (events.js:156:7)
    at TLSSocket.socketOnData (_http_client.js:319:11)'
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  Fatal                '=============== Error Object ==============='
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  Fatal                '{ stack: 'Error: not opened
    at WebSocket.send (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:105178:17)
    at WebSocket.<anonymous> (file:///Applications/Pullover.app/Contents/Resources/app.nw/app.js:2188:24)
    at emitNone (events.js:65:13)
    at WebSocket.emit (events.js:147:7)
    at WebSocket.establishConnection (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:105846:9)
    at ClientRequest.upgrade (file:///Applications/Pullover.app/Contents/Resources/app.nw/vendors.js:105737:26)
    at ClientRequest.g (events.js:240:16)
    at emitThree (events.js:95:13)
    at ClientRequest.emit (events.js:156:7)
    at TLSSocket.socketOnData (_http_client.js:319:11)', message: 'not opened' }'
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon May 15 2017 10:43:06 GMT+0200 (CEST)  PushoverWSClient     'Connected'
Mon May 15 2017 10:44:06 GMT+0200 (CEST)  PushoverWSClient     'Socket closed'
Mon May 15 2017 12:45:39 GMT+0200 (CEST)  ConnectionManager    'Device woke up after 7201s of sleep'
Mon May 15 2017 12:45:49 GMT+0200 (CEST)  ConnectionManager    'Reconnect'
Mon May 15 2017 12:45:49 GMT+0200 (CEST)  ConnectionManager    'fetchAndConnect'
Mon May 15 2017 12:45:49 GMT+0200 (CEST)  PushoverRESTClient   'OpenClient.prototype.fetchNotifications'
Mon May 15 2017 12:45:50 GMT+0200 (CEST)  ConnectionManager    'Received 1 notifications'
Mon May 15 2017 12:45:50 GMT+0200 (CEST)  PushoverRESTClient   'OpenClient.prototype.acknowledgeNotification'
Mon May 15 2017 12:45:50 GMT+0200 (CEST)  ConnectionManager    'Connect to WebSocket'
Mon May 15 2017 12:45:51 GMT+0200 (CEST)  PushoverWSClient     'Socket closed'
Mon May 15 2017 12:45:51 GMT+0200 (CEST)  PushoverWSClient     'Connected'
Mon May 15 2017 12:45:59 GMT+0200 (CEST)  ConnectionManager    'Device woke up after 7s of sleep'
```

**Comment by cgrossde** [comment]
Please try the new alpha, it should be fixed there: [1.3.0-alpha.1](https://github.com/cgrossde/Pullover/releases/tag/1.3.0-alpha.1)
If not please reopen this issue ;)
